# Generated by Django 5.0.7 on 2024-07-31 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_featured_imgage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='featured_imgage',
            new_name='featured_image',
        ),
    ]
